### ISSUE TITLE
RG connection without arm extras

### ISSUE THREAD

**Issue by prajval10** [sharathrjtr/ur10_rg2_ros#3]
This is not an issue with the package, I would like to connect the RG2 gripper directly to the end-effector link of the robot without the arm extras. I tried to change the `rg2.urdf.xacro` : 
```
 <joint name="rg2_joint" type="fixed">
      <origin rpy="0 0 0" xyz="0.218 0 0"/>
      <parent link="${prefix}ee_link"/>
      <child link="${prefix}rg2_body_link"/>
```
However this does not work.

**Comment by sharathrjtr** [comment]
The change you've made in rg2.urdf.xacro is fine. In ur10_robot_rg2_arc.urdf.xacro please change the child link = "ground_base1" to child link = "${robot_prefix1}base_link"
